#! /usr/bin/env python3.2
#This script read the logs and filter for only for specific user for clearing algorithm devising and testing
#In all scripts we should read files line by line and not one at a time since for future large files we will have memory problems otherwise. This also usually assuems that the input is sorted. We should exercise cautions about that too.
logFile = open("../outs/0","r")
outFile = open(r"../outs/1","w")
for line in logFile:
	if "6809274T61RF" in line:
		outFile.write(line)
logFile.close()
outFile.close()
