#!/usr/bin/env python3.2

import sys
import os

usersFile = open("../outs/5","r")

users = usersFile.readlines();

for line in users:
	user = line.split('\t')[0]
	if os.path.isfile("../outs/allusers/"+user+".out")== False:
		os.system("./9_generateFinalOutput_forOne "+ line.split('\t')[0])

userFile.close()
