#!/usr/bin/env python3.2

import sys
import os
from multiprocessing import Process
from multiprocessing import Pool

def f(line):
	user = line.split('\t')[0]
	path = ("../outs/allusers/"+user+".out")
#	if os.path.isfile(path)== False:
#		print(user)
	os.system("./9_generateFinalOutput_forOne "+ user)

usersFile = open("../outs/5","r")

users = usersFile.readlines();

if __name__ == '__main__':
	pool = Pool(processes=3)
	pool.map(f, users)

usersFile.close()
