#!/usr/bin/env python3.2
from itertools import groupby

logFile = open("../outs/0","r")
outFile = open(r"../outs/5","w")

logs = logFile.readlines()

logs = sorted(logs, key = lambda log: log.split()[3])

result = []
for key, group in groupby(logs, lambda log: log.split()[3]):
		result.append(key+'\t'+str(sum(1 for log in group))+'\n')

result = sorted(result, key = lambda line: int(line.split()[1]) , reverse=True)

outFile.writelines(result);

logFile.close()
outFile.close()
